Add MPPA to config script, add machine definition

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -44,6 +44,7 @@ Supported targets:
   x86_32-cygwin        (x86 32 bits, Cygwin environment under Windows)
   x86_64-linux         (x86 64 bits, Linux)
   x86_64-macosx        (x86 64 bits, MacOS X)
+  mppa-linux           (Kalray MPPA, Linux)
   manual               (edit configuration file by hand)
 
 For x86 targets, the "x86_32-" prefix can also be written "ia32-".
@@ -139,6 +140,8 @@ case "$target" in
       arch="powerpc"; model="ppc64"; endianness="big"; bitsize=32;;
   e5500-*)
       arch="powerpc"; model="e5500"; endianness="big"; bitsize=32;;
+  mppa-*)
+      arch="mppa"; model="k1b"; endianness="little"; bitsize=32;;
   manual)
       ;;
   "")
@@ -375,6 +378,33 @@ if test "$arch" = "x86" -a "$bitsize" = "64"; then
 fi
 
 #
+# MPPA Target Configuration
+#
+if test "$arch" = "mppa"; then
+
+  case "$target" in
+    linux)
+        abi="standard"
+        ;;
+    *)
+        echo "Error: invalid eabi/system '$target' for architecture MPPA." 1>&2
+        echo "$usage" 1>&2
+        exit 2;;
+  esac
+
+  casm="${toolprefix}gcc"
+  casm_options="-c"
+  cc="${toolprefix}gcc"
+  clinker="${toolprefix}gcc"
+  cprepro="${toolprefix}gcc"
+  cprepro_options="-std=c99 -U__GNUC__ '-D__REDIRECT(name,proto,alias)=name proto' '-D__REDIRECT_NTH(name,proto,alias)=name proto' -E"
+  libmath="-lm"
+  struct_passing="ints"  # up to 32 bytes
+  struct_return="int1-8" # should really be up to 32 bytes
+  system="linux"
+fi
+
+#
 # Finalize Target Configuration
 #
 if test -z "$casmruntime"; then casmruntime="$casm $casm_options"; fi
@@ -590,6 +620,7 @@ cat >> Makefile.config <<'EOF'
 # ARCH=powerpc
 # ARCH=arm
 # ARCH=x86
+# ARCH=mppa
 ARCH=
 
 # Hardware variant
@@ -602,13 +633,14 @@ ARCH=
 # MODEL=armv7m      # for ARM
 # MODEL=32sse2      # for x86 in 32-bit mode
 # MODEL=64          # for x86 in 64-bit mode
+# MODEL=k1b         # for MPPA k1b core
 MODEL=
 
 # Target ABI
 # ABI=eabi          # for PowerPC / Linux and other SVR4 or EABI platforms
 # ABI=eabi          # for ARM
 # ABI=hardfloat     # for ARM
-# ABI=standard      # for x86
+# ABI=standard      # for x86 and MPPA
 ABI=
 
 # Target bit width
@@ -618,7 +650,7 @@ BITSIZE=
 
 # Target endianness
 # ENDIANNESS=big     # for ARM or PowerPC
-# ENDIANNESS=little  # for ARM or x86
+# ENDIANNESS=little  # for ARM, x86, or MPPA
 ENDIANNESS=
 
 # Default calling conventions for passing structs and unions by value
@@ -648,6 +680,9 @@ STRUCT_RETURN=ref
 # SYSTEM=bsd
 # SYSTEM=macosx
 # SYSTEM=cygwin
+#
+# Possible choices for MPPA:
+# SYSTEM=linux
 SYSTEM=
 
 # C compiler for compiling runtime library files and some tests
